### PR TITLE
Changed ATTs infrastructure to newest ConfigureEndpointTestExecution

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to https://github.com/Particular/NServiceBus/pull/3514#issuecomment-189050351

### CODE REVIEW

**Comment by danielmarbach** [comment]
@janovesk could you take this over? Or maybe someone from @Particular/engineers which is looking for something to get done.

**Comment by SzymonPobiega** [comment]
Looks good!

**Comment by janovesk** [comment]
I see you sneaked in a couple of missing `ConfigureAwait(false)` here @danielmarbach.. (**cough** https://github.com/Particular/NServiceBus.Gateway/pull/17/commits/0be324d8dd2aa116364478bd16ca9a865e269809#diff-7f760f9ce00a5903cfa959aba6b60606R58 **cough**)

**Comment by danielmarbach** [comment]
Are you picking a super old PR? :) it took us a while until all ATT infra was clean

**Comment by danielmarbach** [comment]
And I doubt it was me. Let's see :)

**Pull request merged**
