### PR TITLE
Core V6 Beta Release

### PR DESCRIPTION
**Pull request by mikeminutillo**
Connects to https://github.com/particular/platformdevelopment/issues/757

### CODE REVIEW

**Comment by SimonCropp** [comment]
LGTM @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
is there any current need for this to be in develop or should we wait at least for the rc/prod release until we merge it back into develop?

**Comment by andreasohlund** [comment]
I'm with @timbussmann , no need for this now

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers should we close this in favour of #54 ?

**Pull request closed without merging**
