### PR TITLE
Add SetReplyToUri - release

### PR DESCRIPTION
**Pull request by DavidBoike**

### CODE REVIEW

**Comment by alexisadm** [comment]
Hi @DavidBoike , We testeed this branch on K8s and it works fine.

**Review by timbussmann — APPROVED** [review]

**Comment by DavidBoike** [comment]
@alexisadm Good to hear! I'll work on getting this released.

**Comment by DavidBoike** [comment]
@alexisadm The change is released to NuGet as NServiceBus.Gateway 3.2.0.

Thanks for bringing this to our attention! Sorry it was a bit of a bumpy/twisty road to get to a release.

**Comment by alexisadm** [comment]
Hi All, thanks a lot. David don't worry all is part of process to find a
good solution.

**Pull request merged**
