### PR TITLE
master update dev tooling

### PR DESCRIPTION
**Pull request by seanfarmar**
This updates development tooling on the `master` branch.
Note: This should not be squashed.

### CODE REVIEW

**Comment by bording** [comment]
So it would appear that this is failing because we've diverged the public API between the `net452` and `netstandard2.0` assemblies, which seems incorrect to me.

**Comment by timbussmann** [comment]
should this PR also use the `merge-update-dev-tooling` branch like https://github.com/Particular/NServiceBus.Gateway/pull/118 ?

**Comment by bording** [comment]
@timbussmann No, This is the correct branch. It was created first, and then since there are merge conflicts,the other branch was created to resolve them before merging it back.

**Comment by timbussmann** [comment]
ok, just wanted to verify.

**Pull request merged**
