### PR TITLE
Add ProxyAddress to channel

### PR DESCRIPTION
**Pull request by alexisadm**
Hi all,
As we have talked on this PR (Particular#267), I send a new pull request. target to 3.1  version.

Kind regards,
Alexis

### CODE REVIEW

**Comment by DavidBoike** [comment]
Hey @alexisadm, this is looking like the right direction. I've raised this with the right group internally

I cleared the CI workflow to run. Looks like there are a few minor issues. Are you using a build of this internally right now?

Also, could you please sign our CLA as directed in [this comment](https://github.com/Particular/NServiceBus.Gateway/pull/284#issuecomment-863289617)? It looks like the email on your Git commits doesn't match your GitHub user so you'll have to add that to your GitHub profile before you can sign.

**Comment by alexisadm** [comment]
Hi @DavidBoike , I have pushed a commit that fix tests. And Yes, we are using a build if this internally and testing it on ours K8s cluster.

**Comment by DavidBoike** [comment]
Thanks for pushing that commit and signing the CLA!

I'll take a closer look at this (probably Monday) and try to get it integrated. I'm honestly not sure when we would do a release that would include this, whether we would do a release just for this change or wait for additional enhancements. (If you are a different customer affected by this same thing, please chime in as that would weigh into the decision.) In the meantime @alexisadm I assume you can continue using the version you've built in-house?

**Comment by alexisadm** [comment]
Hi @DavidBoike , I've been trying to understand the approval tests for a while but I can't quite find the solution, I have modified the files "APIApprovals.Approve.netframework.approved.txt" and "APIApprovals.Approve.netframework.received" and netstandard to add the "ProxyAdress" property but they still fail. Could you tell me how can I fix them?

Kind regards,
Alexis

**Comment by DavidBoike** [comment]
Don't worry about the approval tests. We use those to be able to easily spot when we change the public API so we can be sure we don't violate SemVer. You just run the test, and it fails and leaves a *.received.txt, then you use a diff viewer to migrate the changes over the *.approved.txt. On this branch, apparently there was the extra detail that the netstandard vs. netframework approval files were separate, which we don't do anymore - that has been fixed in master where the API Approval library is instructed to leave out the platform attribute so we can approve everything with one file.

But anyway…

I changed the target branch of your PR so I could merge your changes from the fork into a local branch, and then fixed up the acceptance tests, and some minor wording and code style stuff. The result of that is https://github.com/Particular/NServiceBus.Gateway/pull/285.

Then I squashed that and forward-ported it to the master branch, since we are already working on Gateway version 4, which will be for NServiceBus 8 whenever we release that. The result of that is https://github.com/Particular/NServiceBus.Gateway/pull/286.

I still need to verify the change works with its downstream packages (NServiceBus.Gateway.Sql and NServiceBus.Gateway.RavenDB) and document the addition.

**Pull request merged**
