### PR TITLE
[WIP] Update to core v6.1.0

### PR DESCRIPTION
**Pull request by andreasohlund**
WIP until updated to stable 6.1

### CODE REVIEW

**Comment by SimonCropp** [comment]
@andreasohlund still WIP?

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers remind me, the current stance for core minors is to only update the acceptance tests right?

**Comment by bording** [comment]
@andreasohlund That's correct.

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus.Gateway/pull/68

**Pull request closed without merging**
