### PR TITLE
update to core 1587

### PR DESCRIPTION
**Pull request by SimonCropp**
connects to #39

### CODE REVIEW

**Comment by SimonCropp** [comment]
@SzymonPobiega can u review my routing changes here

**Comment by SzymonPobiega** [comment]
I see that the biggest difference is the fact that the callbacks package now requires the instance ID to be present and because it is `EnabledByDefault`, all the tests need to specify it.

How about, instead of using the callbacks package, you simulate this? [Here](https://github.com/Particular/NServiceBus.RabbitMQ/commit/302f2848b69d4fc6728c4fbe75b6b12f9a2a3057#diff-10ce60139aa573b172adda22f364c711R54) I've did similar change in Rabbit. The "trick" is to use `sendOptions.RouteReplyToThisInstance();` when sending a request (this is the only thing callbacks do in V6).

**Comment by adamralph** [comment]
@SimonCropp is there any issue which we can connect this with?

**Comment by SimonCropp** [comment]
@SzymonPobiega the callbacks is only required by the acceptance tests to verify they actually work. not required by the gateway nuspec https://github.com/Particular/NServiceBus.Gateway/blob/develop/packaging/nuget/nservicebus.gateway.nuspec or referenced in the gateway dll  https://github.com/Particular/NServiceBus.Gateway/blob/develop/src/NServiceBus.Gateway/NServiceBus.Gateway.csproj#L46


with that in mind does your comment still stand?

**Comment by SzymonPobiega** [comment]
@SimonCropp yes. The problem with callbacks package I see is that it requires setting up instance ID in each and every endpoint in the acceptance tests. These IDs are not required for gateway so it blurs the tests. 

An alternative would be excluding the callbacks dll from scanning in the test infrastructure and include it only in that one test that refers to callbacks.

**Comment by SzymonPobiega** [comment]
Let me try to validate that approach.

**Comment by SimonCropp** [comment]
@SzymonPobiega ok cool. feel free to push directly to this branch/pr

**Comment by SzymonPobiega** [comment]
OK, I give up. The gateway in its current shape is broken beyond repair... One thing only: the tests `When_doing_request_reply` and `When_doing_request_reply_between_sites` seem to be almost identical. Not sure if we need both.

**Comment by danielmarbach** [comment]
ping @janovesk

**Comment by janovesk** [comment]
> OK, I give up. The gateway in its current shape is broken beyond repair...

That's a big statement. Can you be a bit more explicit: what is broken? @SzymonPobiega

**Comment by SzymonPobiega** [comment]
@janovesk that was a moment of frustraction. I meant, I cannot be repaired in the sense of having more than one URL per site.

**Comment by timbussmann** [comment]
so is this one ready for merging? @SzymonPobiega @SimonCropp

**Comment by SzymonPobiega** [comment]
:+1:

**Pull request merged**
